server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum_sys?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: niit1234
    driver-class-name=com: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 10
      max-active: 50
      max-idle: 30
      min-idle: 10
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis:
    type-aliases-package: com.xbb.entity
    mapper-locations: classpath:mapper/*.xml
debug: true
logging:
  level:
    com.xbb.mapper: debug
multipart:
  maxFileSize: 3000MB
  maxRequestSize: 10000MB
